# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    app.uw_forum_enabled: '%env(bool:UW_FORUM_ENABLED)%'
    app.uw_construction_time_override: '%env(default::int:UW_CONSTRUCTION_TIME_OVERRIDE)%'
    app.uw_research_time_override: '%env(default::int:UW_RESEARCH_TIME_OVERRIDE)%'
    app.uw_fleet_travel_time_override: '%env(default::int:UW_FLEET_TRAVEL_TIME_OVERRIDE)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    FrankProjects\UltimateWarfare\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    FrankProjects\UltimateWarfare\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    FrankProjects\UltimateWarfare\Service\GameEngine\Processor\ConstructionProcessor:
        arguments:
            $constructionTimeOverride: '%app.uw_construction_time_override%'

    FrankProjects\UltimateWarfare\Service\GameEngine\Processor\ResearchProcessor:
        arguments:
            $researchRegistry: '@FrankProjects\UltimateWarfare\Repository\ResearchRegistry'
            $researchTimeOverride: '%app.uw_research_time_override%'

    Symfony\Component\HttpFoundation\Session\Storage\Handler\PdoSessionHandler:
        arguments:
            - '%env(DATABASE_URL)%'
