# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    app.uw_chat_hostname: '%env(UW_CHAT_HOSTNAME)%'
    app.uw_chat_address: '%env(UW_CHAT_ADDRESS)%'
    app.uw_chat_service_port: '%env(UW_CHAT_SERVICE_PORT)%'
    app.uw_chat_public_port: '%env(UW_CHAT_PUBLIC_PORT)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    FrankProjects\UltimateWarfare\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    FrankProjects\UltimateWarfare\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    ReCaptcha\ReCaptcha:
        arguments:
            - '%env(GOOGLE_RECAPTCHA_SECRET_KEY)%'
