FrankProjects\UltimateWarfare\Entity\GameUnit:
    type: entity
    table: game_unit
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 20
            options:
                fixed: false
        nameMulti:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
            column: name_multi
        rowName:
            type: string
            nullable: false
            length: 20
            options:
                fixed: false
            column: row_name
        image:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
        networth:
            type: integer
            nullable: false
            options:
                unsigned: false
        timestamp:
            type: integer
            nullable: false
            options:
                unsigned: true
        description:
            type: text
            nullable: false
            length: 255
            options:
                fixed: false
    oneToMany:
        worldRegionUnits:
            targetEntity: WorldRegionUnit
            mappedBy: gameUnit
        constructions:
            targetEntity: Construction
            mappedBy: gameUnit
        fleetUnits:
            targetEntity: FleetUnit
            mappedBy: gameUnit
    manyToOne:
        gameUnitType:
            targetEntity: GameUnitType
            inversedBy: gameUnits
            joinColumn:
                name: game_unit_type_id
                referencedColumnName: id
    lifecycleCallbacks: {  }
    embedded:
        battleStats:
            class: FrankProjects\UltimateWarfare\Entity\GameUnit\BattleStats
        cost:
            class: FrankProjects\UltimateWarfare\Entity\GameUnit\Cost
        income:
            class: FrankProjects\UltimateWarfare\Entity\GameUnit\Income
        upkeep:
            class: FrankProjects\UltimateWarfare\Entity\GameUnit\Upkeep
