FrankProjects\UltimateWarfare\Entity\History:
    type: entity
    table: history
    indexes:
        world:
            columns:
                - world_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        worldId:
            type: integer
            nullable: false
            options:
                unsigned: true
            column: world_id
        name:
            type: string
            nullable: false
            length: 64
            options:
                fixed: false
        endDate:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: end_date
    lifecycleCallbacks: {  }
