FrankProjects\UltimateWarfare\Entity\HistoryPlayer:
    type: entity
    table: history_player
    indexes:
        world:
            columns:
                - world_id
        user_id:
            columns:
                - user_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        worldId:
            type: integer
            nullable: false
            options:
                unsigned: true
            column: world_id
        playerName:
            type: string
            nullable: false
            length: 32
            options:
                fixed: false
            column: player_name
        userId:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: user_id
        federationId:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: federation_id
        regions:
            type: integer
            nullable: false
            options:
                unsigned: false
        networth:
            type: integer
            nullable: false
            options:
                unsigned: false
    lifecycleCallbacks: {  }
