FrankProjects\UltimateWarfare\Entity\WorldRegion:
    type: entity
    table: world_region
    indexes:
        worldxy:
            columns:
                - world_id
                - x
                - y
    uniqueConstraints:
        unique_world_region:
            columns: [ x, y, world_id ]
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        x:
            type: integer
            nullable: false
            options:
                unsigned: true
        y:
            type: integer
            nullable: false
            options:
                unsigned: true
        z:
            type: integer
            nullable: false
            options:
                unsigned: true
        type:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        state:
            type: integer
            nullable: false
            options:
                unsigned: true
                default: '0'
        name:
            type: string
            nullable: true
            length: 32
            options:
                fixed: false
        space:
            type: smallint
            nullable: false
            options:
                unsigned: false
                default: '1000'
        population:
            type: integer
            nullable: false
            options:
                unsigned: true
                default: '0'
    oneToMany:
        worldRegionUnits:
            targetEntity: WorldRegionUnit
            mappedBy: worldRegion
        constructions:
            targetEntity: Construction
            mappedBy: worldRegion
        fleets:
            targetEntity: Fleet
            mappedBy: worldRegion
        targetFleets:
            targetEntity: Fleet
            mappedBy: targetWorldRegion
    manyToOne:
       world:
           targetEntity: World
           inversedBy: worldRegions
           joinColumn:
               name: world_id
               referencedColumnName: id
       player:
           targetEntity: Player
           inversedBy: worldRegions
           joinColumn:
               name: player_id
               referencedColumnName: id
    lifecycleCallbacks: {  }
