FrankProjects\UltimateWarfare\Entity\WorldCountry:
    type: entity
    table: world_country
    uniqueConstraints:
        unique_world_country:
            columns: [ x, y, sector_id ]
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        x:
            type: integer
            nullable: false
            options:
                unsigned: true
        y:
            type: integer
            nullable: false
            options:
                unsigned: true
        image:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
    oneToMany:
        worldRegions:
            targetEntity: WorldRegion
            mappedBy: worldCountry
    manyToOne:
       worldSector:
           targetEntity: WorldSector
           inversedBy: worldCountries
           joinColumn:
               name: sector_id
               referencedColumnName: id
    lifecycleCallbacks: {  }
