FrankProjects\UltimateWarfare\Entity\World\MapConfiguration:
  type: embeddable
  fields:
    size:
      type: integer
      nullable: false
      options:
        unsigned: true
    persistence:
      type: float
      nullable: false
      options:
        unsigned: true
    seed:
      type: integer
      nullable: false
      options:
        unsigned: true
    waterLevel:
      type: integer
      nullable: false
      options:
        unsigned: true
    beachLevel:
      type: integer
      nullable: false
      options:
        unsigned: true
    forrestLevel:
      type: integer
      nullable: false
      options:
        unsigned: true